# Configuración de Netlify para Andes Runners
# Configuración mínima para resolver problemas de MIME type

[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones para SPA con soporte bilingüe
[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
