# Configuración de Netlify para Andes Runners MVP
# Optimizado para despliegue rápido y eficiente

[build]
  publish = "dist"
  command = "npm ci && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Performance optimizations
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Enable build optimizations
  NETLIFY_SKIP_EDGE_HANDLERS_INSTALL = "true"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para optimización y seguridad
[[headers]]
  # Headers para HTML files (no cache for SPA routing)
  for = "/*.html"
    [headers.values]
    # Seguridad
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://analytics.tiktok.com https://*.tiktok.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: https://*.tiktok.com; connect-src 'self' https://www.google-analytics.com https://analytics.tiktok.com https://*.tiktok.com; frame-src 'self' https://docs.google.com;"

# Configuración específica para archivos estáticos con optimización de performance
[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"
    # Performance headers
    X-Content-Type-Options = "nosniff"

# Preload critical resources
[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Enable compression
    Content-Encoding = "gzip"

# Specific headers for onboarding script
[[headers]]
  for = "/js/andes-simplified-onboarding.js"
    [headers.values]
    Cache-Control = "no-cache, must-revalidate"
    Content-Type = "application/javascript"

[[headers]]
  for = "/es/js/andes-simplified-onboarding.js"
    [headers.values]
    Cache-Control = "no-cache, must-revalidate"
    Content-Type = "application/javascript"
[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración de plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
