# Configuración de Netlify para Andes Runners MVP
# Optimizado para despliegue rápido y eficiente

[build]
  # Directorio donde se encuentran los archivos de construcción
  publish = "dist"
  # Comando para construir el sitio
  command = "npm run build"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para optimización y seguridad
[[headers]]
  # Headers para todos los archivos
  for = "/*"
    [headers.values]
    # Seguridad
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache para recursos estáticos
    cache-control = '''
    max-age=31536000,
    no-cache,
    no-store,
    must-revalidate'''

# Configuración específica para archivos estáticos
[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración de plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
